version: 2
models:
- name: adwords_click_performance
  columns:
  - name: gclid
    tests:
    - not_null
    - unique
- name: adwords_criteria_performance
  columns:
  - name: id
    tests:
    - not_null
    - unique
- name: adwords_url_performance
  columns:
  - name: id
    tests:
    - not_null
    - unique
- name: adwords_accounts
  columns:
  - name: account_id
    tests:
    - not_null
    - unique
- name: adwords_ad_groups
  columns:
  - name: ad_group_id
    tests:
    - not_null
    - unique
- name: adwords_ads
  columns:
  - name: ad_id
    tests:
    - not_null
    - unique
- name: adwords_campaigns
  columns:
  - name: campaign_id
    tests:
    - not_null
    - unique